### ISSUE TITLE
Recoger información básica (para empezar)

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#1]
Recopilar información sobre todo lo que fuimos haciendo (los diferentes pasos).

**Comment by JJ** [comment]
¿Encargado a alguien? 
A ver, si mal no recuerdo, hicimos
- Visualización con SOM
- Preprocesado de datos, eliminando variables irrelevantes
- Uso de WEKA sobre lo obtenido.

**Comment by JJ** [comment]
¿Tenemos ya la información básica?

**Comment by pacastillo** [comment]
Tengo los documentos que guardaba Antonio y los que tenía yo. Tengo que ordenarlos. Esta semana que viene podemos verlo tranquilamente.
