### ISSUE TITLE
Buscar los datos completos

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#2]
(1) los que nos facilitaron, los datos en bruto, sin limpiar.
(2) los que finalmente, ya limpios, se usaron.

**Comment by JJ** [comment]
Yo debo tenerlos en el portátil. ¿Tú no los tienes?

**Comment by pacastillo** [comment]
pues algunos tengo, pero tengo que revisarlos bien...

**Comment by amorag** [comment]
Leches, que no sabía de qué iba esto. XD

Yo tengo todos los datos y los procesos que les fuimos haciendo.
¿Dónde/Cuándo se quiere enviar?
Esta semana la tengo hasta arribísima. :_(

**Comment by JJ** [comment]
¿Tenemos ya estos datos? Antonio los pasó por Dropbox.

**Comment by amorag** [comment]
Si, los pasé.
Creo que están todos.

Y varios informes útiles. ;)

**Comment by pacastillo** [comment]
Sí, lo tengo todo. Antonio, esta misma semana quedamos un rato para comentarlos.
