### ISSUE TITLE
Reduce Table 3

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015_books#24]
It's longer than the text. I prefer not to screw anything but if nobody wants to do it, I can try.

**Comment by unintendedbear** [comment]
The same for Fig. 1 :(

**Comment by fergunet** [comment]
I know how to do it :)

**Comment by unintendedbear** [comment]
Ok! My problem was because I didn't want to change too much the format, size, whatever, with regard to the other tables... 
Thank you :D
