### ISSUE TITLE
Put the paper in format of Expert Systems With Applications journal. Fix the tables and figures according to the width of the pages

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2015_books#28]
It is Elsevier's format:

https://www.elsevier.com/authors/author-schemas/latex-instructions

**Comment by amorag** [comment]
Please Hossam, do the change of format.;D

**Comment by fergunet** [comment]
If Hossam does not have time I can also do it :)

2016-05-10 19:55 GMT+02:00 Antonio Mora notifications@github.com:

> Please Hossam, do the change of format.;D
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015_books/issues/28#issuecomment-218238094

## 

Dr. Pablo García Sánchez
University of Granada
http://www.ugr.es/~pablogarcia

**Comment by amorag** [comment]
Ok, please, go ahead Pablo.;)

Thanks!
