### ISSUE TITLE
Describir el proceso de análisis y "limpieza"

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#3]
Recuerdo que se usó el SOM, y ¿alguna otra herramienta?

Recoger información sobre el proceso de reducción del conjunto de entradas.

**Comment by JJ** [comment]
U-matrix, pero es una herramienta sobre el SOM.

**Comment by amorag** [comment]
Hicimos varios análisis sobre los datos (aparte de SOM, estudiando la hoja Excel), eliminando errores y columnas inútiles en base a preguntas que le hicimos a Santiago.
