### ISSUE TITLE
Improve and finish the SotA section

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2015_books#31]
Please, follow the comments and answer/address them.
Then delete these comments. :D

Thanks!

**Comment by pacastillo** [comment]
I have reviewed the SoA.
Many sentences have been rewritten, and now reading this section is much more "smooth".

I hope now it has been improved   :)

**Comment by amorag** [comment]
Thank you Pedro.
Yes, you have improved the section, so far. ;D
