### ISSUE TITLE
Abbreviate journals in bibliography

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015_books#32]
Required by the journal.

Journal list: http://www.issn.org/services/online-services/access-to-the-ltwa/

**Comment by JJ** [comment]
That should be a matter of the Bib style file. I think it's only necessary
to add "abbrv"

2016-05-12 16:16 GMT+02:00 Pablo García Sánchez notifications@github.com:

> Required by the journal.
> 
> Journal list:
> http://www.issn.org/services/online-services/access-to-the-ltwa/
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015_books/issues/32

## 

JJ
