### ISSUE TITLE
Preliminary Analysis of the Dataset

### ISSUE THREAD

**Issue by deantares** [geneura-papers/2015_books#33]
I'm sorry. I haven't time to make a huge description of the chart right now. But i want share it with you.

![hist_variables](https://cloud.githubusercontent.com/assets/1782996/15253084/f1cc0bfa-1930-11e6-9c5b-66064cde260d.jpg)
![density_variables](https://cloud.githubusercontent.com/assets/1782996/15253091/f5b619c2-1930-11e6-9391-20e829f374ab.jpg)
![x-d_density](https://cloud.githubusercontent.com/assets/1782996/15253092/f960ec6e-1930-11e6-86c0-e16c9dd6fec3.jpg)

**Comment by pacastillo** [comment]
¡great!
Thank you so much!

This should be included in the next paper on book-sales forecasting  :)
