### ISSUE TITLE
Descripción de los métodos finalmente utilizados

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#4]
Se probaron: MLP, J48 y M5P.

**Comment by JJ** [comment]
No recuerdo cuál se usó al final.

**Comment by pacastillo** [comment]
¡precisamente!    ;)
por eso tengo que hacer introspección, y recordar lo que se hizo (y cómo).

**Comment by amorag** [comment]
Yo tengo los documentos que preparé para cada reunión, con los métodos usados y los resultados obtenidos. ;)

Teníamos resultados de M5P, M5Rules, DecisionTable y RepTree.

**Comment by JJ** [comment]
¿Resolvemos esto entonces y se va pasando al paper?

**Comment by pacastillo** [comment]
Si tenéis por ahí descripciones, se podrían ir incluyendo en el TEX.
