### ISSUE TITLE
Add more details about CFS and RelieFF

### ISSUE THREAD

**Issue by 7ossam81** [geneura-papers/2015_books#42]
This is related to the 1st comment of reviewer#1.

**Comment by pacastillo** [comment]
(1) "When CFS is used for regression, please to introduce how to estimate correlations between each feature and output (total sales)." 

(2) "Since RReliefF, as a variant of ReliefF, is special for regression, why do not the authors use RReliefF ?"

**Comment by 7ossam81** [comment]
Done. @pacastillo Please check and close if it is ok.
