### ISSUE TITLE
Why is MLP with one hidden layer described in 5.1?

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#43]
Justify this issue.

**Comment by 7ossam81** [comment]
MLP will be added to the experiments. So the existence of its description is justified.
I don't think the reviewer means why only "one" hidden layer is used. Anyway, MLP is the most common architecture used in the literature and it was proven that any feedforward neural network with a single hidden layer is able to approximate any continuous function.

**Comment by pacastillo** [comment]
Yes, i agree with you    :)

The thing is that the reviewer found the description, but not the MLP results (I think this is the problem in this issue).

**Comment by 7ossam81** [comment]
Great. I started to do the experiments of MLP and ELM and I will add them soon ;)

**Comment by pacastillo** [comment]
I have given the justification (response) to the reviewer's comment.
