### ISSUE TITLE
M5P and RF themselve embed feature selection procedure...

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#44]
Do we have to include the "selection" these methods automatically carry out?

**Comment by unintendedbear** [comment]
I think it would be interesting to study if the features these algorithms select are the same we select by performing FR separately.
The same way, do they reduce the feature set again or do they take all the features from the FS part as good and they don't select anymore?
It's true that with these conditions and without clarifying the process it's not fair to include them in table 3.

**Comment by fergunet** [comment]
We should check if M5P and RF ALWAYS do the feature selection, or if it is optional when launching them. @7ossam81 do you remember it?
