### ISSUE TITLE
The authors should add the recommend systems into the future work part

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#46]
related to R2(comment 3)

**Comment by unintendedbear** [comment]
I think that if we have clear reasons why we didn't use this instead of the proposed method, we can even include this in the state of the art. If not, I can search for ways to apply recommender systems to the problem.

**Comment by 7ossam81** [comment]
According to the reviewer's comments I think it is clear that we just need to add a simple statement about applying recommendation systems in our future work. Simply, this statement could be added to the conclusion.

**Comment by unintendedbear** [comment]
Oh, ok, it was just in case you wanted to justify why or say how could we apply them, but if it's just that, forget what I said. Sorry!
