### ISSUE TITLE
sections 4.1 and 4.2 should be moved to section 2

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#47]
related to R3(comment 2)

**Comment by unintendedbear** [comment]
Hi all,

I wanted to start reviewing the paper but there are still important changes to do, so maybe there's no point in doing that right now. What I can do instead is going through sections 2 and 4 and help with this issue, if you want. What do you think?

**Comment by pacastillo** [comment]
Don't worry (and thank you :)
I will move those sections today.
