### ISSUE TITLE
manuscript should show a flowchart of the proposed forecasting scheme and describe it

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#48]
related to R3(comment 3)

**Comment by amorag** [comment]
The re-opener is here. :D

I think the figure should specify a bit deeper the methodology.
Thus I propose to include in each block something like:

DATA COLLECTION: 
6000 real books - 50 features

PREPROCESSING:
Select pre-sales data, feature refinement

FEATURE SELECTION:
SOM, RelFAttEval, CFSubEval

FORECASTING:
Regression techniques (kNN, M5P, RF, LR, SVM, MLP, ELM)

VALIDATION:
Decision Trees/Regression Models

What do you think?

**Comment by pacastillo** [comment]
Ok   :)
