### ISSUE TITLE
Make awesome plots to replace the tables.

### ISSUE THREAD

**Issue by deantares** [geneura-papers/2015_books#52]
I need to know. What do we will compare?  

We can compare "All attributes" vs "ReliefFAttributeEval-FS":

![1](https://cloud.githubusercontent.com/assets/1782996/18176759/5d3898d4-7077-11e6-843e-55a1752cdc3e.png)

Or we can compare all the forecast methods between them for the different dataset (Publisher + Attribute selection):

![2](https://cloud.githubusercontent.com/assets/1782996/18176764/6119449e-7077-11e6-93d2-791c4cd8fef9.png)

Or we can make both of them. It's free!

For other hand. What metrics do we will use? In my opinion, to use metrics "high is better" (R square) and "low is bettler" (the others) in the same plot it's a mistake. We can handle a single plot for a interesting metric:

![time](https://cloud.githubusercontent.com/assets/1782996/18176924/11f76b06-7078-11e6-91bd-04b03999b1d3.png)

**Comment by amorag** [comment]
Sorry, I think we need more awesome plots... XD

**Comment by 7ossam81** [comment]
What do you mean @amorag  ? another type of plots ?

**Comment by amorag** [comment]
No, I meant that we needed more plots (for old Tables 3 and 5), not just the one we had.

Antares has created them already, no, nomore plots are needed (just to fix a few little things). ;D
