### ISSUE TITLE
Adress rev1, comment 3

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015_books#54]
There is no change in the paper, just a response. Some change, even if it is simply copying the explanation to the reviewer, should be made.

**Comment by amorag** [comment]
I have addressed this by adding the sentence:

"It is important to note that both RF and M5P have an embedded feature selection mechanism (the variables which compose the final trees), however this is part of their inherent procedure. In the following section we will apply three filter-based feature selection techniques on the dataset, so all the methods will profit."

It is at the end of section 5.2 and before 5.3 where the Feature selection is applied.

Is it correct?
What do you think?
