### ISSUE TITLE
traducir los nombres de las variables que describen cada libro

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_books#7]
Necesito ayuda para traducir los nombres de las variables que describen cada libro:

referencia
autor
pvp
materia1
materia2
materia3
editorial
coleccion
encuadernacion
tirada
venta_total
venta_grandes_superficies
venta_delegados
venta_resto
venta1anio_total
venta1anio_grandes_superficies
venta1anio_delegados
venta1anio_resto
colocado_total
colocado_grandes_superficies
colocado_delegados
colocado_resto
colocado1anio_total
colocado1anio_grandes_superficies
colocado1anio_delegados
colocado1anio_resto
reimpresiones
numero_reimpresiones
devolucion_total
devolucion_grandes_superficies
devolucion_delegados
devolucion_resto
devolucion1anio_total
devolucion1anio_grandes_superficies
devolucion1anio_delegados
devolucion1anio_resto
obsequios
ejemplares_distribuidos_en_novedad
puntos_vta_total
puntos_vta_grandes_superficies
puntos_vta_delegados
puntos_vta_resto
puntos_vta1anio_total
puntos_vta1anio_grandes_superficies
puntos_vta1anio_delegados
puntos_vta1anio_resto
semanas_venta
entorno_venta_positivo
entorno_venta_medio
entorno_venta_negativo

**Comment by pacastillo** [comment]
Los dejo en el archivo de texto para traducirlo ahí.

(por cierto, no he podido asignar el issue a más de uno)

**Comment by JJ** [comment]
OK.

2015-08-07 18:59 GMT+02:00 Pedro A. Castillo Valdivieso <
notifications@github.com>:

> Los dejo en el archivo de texto para traducirlo ahí.
> 
> (por cierto, no he podido asignar el issue a más de uno)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015_books/issues/7#issuecomment-128765831
> .

## 

JJ

**Comment by JJ** [comment]
Si quieres asignar a varios no tienes más que mencionarlo con @ en el issue.

El 7 de agosto de 2015, 19:02, JJ Merelo jjmerelo@gmail.com escribió:

> OK.
> 
> 2015-08-07 18:59 GMT+02:00 Pedro A. Castillo Valdivieso <
> notifications@github.com>:
> 
> > Los dejo en el archivo de texto para traducirlo ahí.
> > 
> > (por cierto, no he podido asignar el issue a más de uno)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/geneura-papers/2015_books/issues/7#issuecomment-128765831
> > .
> 
> ## 
> 
> JJ

## 

JJ

**Comment by pacastillo** [comment]
Guay, 
¡otra cosa que aprendo para la siguiente!    ;)

**Comment by amorag** [comment]
Hecho.
Echadles un ojo.

No cierro el issue hasta que no les deis el visto bueno. ;)

**Comment by pacastillo** [comment]
Ok.
Tienen buena pinta  ;)   Los reviso esta tarde.
