### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015_books#9]
```
LaTeX Warning: File `som43vars.eps' not found on input line 445.


! LaTeX Error: File `som43vars.eps' not found.

\epsfig{file=som43umatrix.eps,width=5cm}

```

¿Por qué usáis todavía epsfig en vez del nuevo `includegraphics`?

**Comment by pacastillo** [comment]
lo siento, olvidé añadir los archivos EPS al repo remoto!!!!!!!        :|

Arreglado.

**Comment by pacastillo** [comment]
lo siento, olvidé añadir los archivos EPS al repo remoto!!!!!!!        :|

Arreglado.
